version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./.docker_data/mongodb:/data/db
    networks:
      - lognet
  bot:
    build: ./
    restart: always
    volumes:
      - './:/usr/src/app'
    tty: true
    networks:
      - lognet
    environment:
      - BOT_TOKEN
      - MONGO_URL


 
networks:
  lognet:
    driver: bridge